# Generated by Django 5.2.6 on 2025-11-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('face_shape', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('hair_length', models.CharField(max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('haircut_styles_ids', models.TextField(blank=True, default='[]')),
                ('beard_styles_ids', models.TextField(blank=True, default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BeardStyleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
                ('suitable_for_shapes', models.JSONField(default=list, help_text='Lista de formas de rostro compatibles')),
                ('benefits', models.JSONField(default=list, help_text='Beneficios del estilo')),
                ('tags', models.JSONField(default=list, help_text='Etiquetas del estilo')),
                ('maintenance_level', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='medio', max_length=20)),
                ('popularity_score', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'beard_styles',
                'ordering': ['-popularity_score', 'name'],
                'indexes': [models.Index(fields=['is_active', '-popularity_score'], name='beard_style_is_acti_003d50_idx')],
            },
        ),
        migrations.CreateModel(
            name='HaircutStyleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
                ('suitable_for_shapes', models.JSONField(default=list, help_text='Lista de formas de rostro compatibles')),
                ('suitable_for_gender', models.JSONField(default=list, help_text='Lista de géneros compatibles')),
                ('hair_length_required', models.JSONField(default=list, help_text='Longitudes de cabello requeridas')),
                ('benefits', models.JSONField(default=list, help_text='Beneficios del estilo')),
                ('tags', models.JSONField(default=list, help_text='Etiquetas del estilo')),
                ('difficulty_level', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Medio'), ('dificil', 'Difícil')], default='medio', max_length=20)),
                ('popularity_score', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'haircut_styles',
                'ordering': ['-popularity_score', 'name'],
                'indexes': [models.Index(fields=['is_active', '-popularity_score'], name='haircut_sty_is_acti_4b9538_idx')],
            },
        ),
    ]
