# Generated by Django 5.2.6 on 2025-11-12 23:38

import apps.recomendations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beardstylemodel',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='beardstylemodel',
            name='beard_style_is_acti_003d50_idx',
        ),
        migrations.RemoveField(
            model_name='beardstylemodel',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='haircutstylemodel',
            name='image_url',
        ),
        migrations.AddField(
            model_name='beardstylemodel',
            name='image',
            field=models.ImageField(default='', help_text='Imagen del estilo de barba', upload_to='styles/haircuts/beards/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='haircutstylemodel',
            name='gender',
            field=models.CharField(choices=[('men', 'Hombre'), ('women', 'Mujer')], default='men', help_text='Género al que aplica el estilo (men o women)', max_length=5),
        ),
        migrations.AddField(
            model_name='haircutstylemodel',
            name='image',
            field=models.ImageField(default='', help_text='Imagen del estilo de corte de cabello', upload_to=apps.recomendations.models.haircut_upload_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beardstylemodel',
            name='benefits',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='beardstylemodel',
            name='maintenance_level',
            field=models.CharField(default='medio', max_length=20),
        ),
        migrations.AlterField(
            model_name='beardstylemodel',
            name='suitable_for_shapes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='beardstylemodel',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='haircutstylemodel',
            name='benefits',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='haircutstylemodel',
            name='difficulty_level',
            field=models.CharField(default='medio', max_length=20),
        ),
        migrations.AlterField(
            model_name='haircutstylemodel',
            name='hair_length_required',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='haircutstylemodel',
            name='suitable_for_gender',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='haircutstylemodel',
            name='suitable_for_shapes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='haircutstylemodel',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
