# Generated by Django 5.2.6 on 2025-11-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendations', '0002_alter_beardstylemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beardstylemodel',
            name='image',
            field=models.ImageField(help_text='Imagen del estilo de barba', upload_to='beards/'),
        ),
        migrations.AlterField(
            model_name='haircutstylemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='haircuts/'),
        ),
    ]
