# Generated by Django 5.2.6 on 2025-11-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendations', '0003_alter_beardstylemodel_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='haircutstylemodel',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='haircutstylemodel',
            name='haircut_sty_is_acti_4b9538_idx',
        ),
        migrations.AlterField(
            model_name='haircutstylemodel',
            name='difficulty_level',
            field=models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Medio'), ('dificil', 'Difícil')], default='medio', max_length=10),
        ),
        migrations.AlterModelTable(
            name='haircutstylemodel',
            table=None,
        ),
    ]
