# Generated by Django 5.2.6 on 2025-11-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendations', '0004_alter_haircutstylemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beardstylemodel',
            options={'verbose_name': 'Estilo de Barba', 'verbose_name_plural': 'Estilos de Barba'},
        ),
        migrations.AddField(
            model_name='beardstylemodel',
            name='difficulty_level',
            field=models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Medio'), ('dificil', 'Difícil')], default='medio', max_length=10),
        ),
        migrations.AlterField(
            model_name='beardstylemodel',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen del estilo de barba', null=True, upload_to='beards/'),
        ),
        migrations.AlterField(
            model_name='beardstylemodel',
            name='maintenance_level',
            field=models.CharField(default='medio', help_text='Nivel de mantenimiento requerido', max_length=20),
        ),
    ]
