# Generated by Django 5.2.6 on 2025-11-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendations', '0005_alter_beardstylemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beardstylemodel',
            name='suitable_for_shapes',
            field=models.JSONField(blank=True, default=list, help_text="Formas de rostro adecuadas (usa valores como 'oval', 'redondo', 'cuadrado', etc.)"),
        ),
    ]
