# Generated by Django 5.2.6 on 2025-11-10 04:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_shape', models.CharField(help_text='Forma facial detectada', max_length=50, verbose_name='Forma de rostro')),
                ('confidence', models.FloatField(help_text='Nivel de confianza del análisis (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Confianza')),
                ('analysis_data', models.JSONField(blank=True, help_text='Datos completos del análisis en formato JSON', null=True, verbose_name='Datos del análisis')),
                ('recommendations_data', models.JSONField(blank=True, help_text='Recomendaciones completas en formato JSON', null=True, verbose_name='Datos de recomendaciones')),
                ('recommendations_count', models.IntegerField(default=0, verbose_name='Cantidad de recomendaciones')),
                ('pdf_path', models.CharField(blank=True, help_text='Ruta relativa del PDF generado', max_length=500, null=True, verbose_name='Ruta del PDF')),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='analysis_images/%Y/%m/%d/', verbose_name='Imagen del Análisis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de análisis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facial_analysis_history', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Análisis',
                'verbose_name_plural': 'Historial de Análisis',
                'db_table': 'feedback_analysishistorymodel',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Calificación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación')),
                ('liked', models.BooleanField(blank=True, help_text='True=Like, False=Dislike, None=Sin calificar', null=True, verbose_name='Me gusta')),
                ('comment', models.TextField(blank=True, help_text='Comentario opcional del usuario', max_length=500, null=True, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('analysis_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='feedback.analysishistorymodel', verbose_name='Historial de Análisis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'db_table': 'feedback_feedbackmodel',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='analysishistorymodel',
            index=models.Index(fields=['user', '-created_at'], name='feedback_an_user_id_db1f1e_idx'),
        ),
        migrations.AddIndex(
            model_name='analysishistorymodel',
            index=models.Index(fields=['face_shape'], name='feedback_an_face_sh_422380_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackmodel',
            index=models.Index(fields=['user', '-created_at'], name='feedback_fe_user_id_0aeb80_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackmodel',
            index=models.Index(fields=['analysis_history'], name='feedback_fe_analysi_d192ae_idx'),
        ),
    ]
