# Generated by Django 5.2.6 on 2025-10-20 15:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'auth_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Masculino'), ('female', 'Femenino'), ('other', 'Otro'), ('prefer_not_to_say', 'Prefiero no decir')], max_length=20, null=True)),
                ('hair_length', models.CharField(blank=True, choices=[('short', 'Corto'), ('medium', 'Medio'), ('long', 'Largo'), ('bald', 'Sin cabello')], max_length=20, null=True)),
                ('face_shape', models.CharField(blank=True, choices=[('oval', 'Ovalado'), ('round', 'Redondo'), ('square', 'Cuadrado'), ('heart', 'Corazón'), ('diamond', 'Diamante'), ('oblong', 'Oblongo')], max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth_app.usermodel')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'db_table': 'auth_profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
