# Generated by Django 5.2.6 on 2025-10-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='hair_length',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Altura en metros (ej: 1.75)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='face_shape',
            field=models.CharField(blank=True, choices=[('oval', 'Ovalado'), ('round', 'Redondo'), ('square', 'Cuadrado'), ('heart', 'Corazón'), ('diamond', 'Diamante'), ('oblong', 'Oblongo')], help_text='Se detecta automáticamente mediante análisis facial', max_length=20, null=True),
        ),
    ]
